apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-app
  template:
    metadata:
      labels:
        app: travel-app
    spec:
      containers:
        - name: travel-container
          image: dhanihaneesha/travel-app:v1
          ports:
            - containerPort: 5000
