apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  selector:
    app: travel-app # must match deployment labels
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
      nodePort: 30083
  type: NodePort
